//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hosital_information
    {
        public Hosital_information()
        {
            this.Children_information = new HashSet<Children_information>();
        }
    
        public string HospitalName { get; set; }
        public string HospitalLocation { get; set; }
        public int HospitalCode { get; set; }
        public string TimeofBirth { get; set; }
        public int HospitalID { get; set; }
    
        public virtual ICollection<Children_information> Children_information { get; set; }
    }
}
